# Generated by Django 4.2.3 on 2023-11-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_image_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
