# Generated by Django 4.2.3 on 2023-11-14 08:30

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_nickname_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname_color',
            field=models.CharField(default=users.models.generate_random_color, max_length=7),
        ),
    ]
