# Generated by Django 4.2.3 on 2023-11-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_comment_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
